---
title: "345 Final Project"
author: "Colin Kalsbeek, Abby Schmidt, Katie Erlandson"
date: "4/21/2022"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
```

```{r,eval=FALSE}
## Read in top 100 songs for each year from 1958-2021
## URLs for the years 2012 and 2013 contained no data so they were omitted from analysis
url_58 = "https://en.wikipedia.org/wiki/Billboard_year-end_top_50_singles_of_1958"
url_59 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1959"
url_60 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1960"
url_61 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1961" 
url_62 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1962"
url_63 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1963"
url_64 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1964"
url_65 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1965"
url_66 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1966"
url_67 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1967"
url_68 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1968"
url_69 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1969"
url_70 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1970"
url_71 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1971"
url_72 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1972"
url_73 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1973"
url_74 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1974"
url_75 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1975"
url_76 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1976"
url_77 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1977"
url_78 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1978"
url_79 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1979"
url_80 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1980"
url_81 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1981"
url_82 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1982"
url_83 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1983"
url_84 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1984"
url_85 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1985"
url_86 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1986"
url_87 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1987"
url_88 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1988"
url_89 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1989"
url_90 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1990"
url_91 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1991"
url_92 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1992"
url_93 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1993"
url_94 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1994"
url_95 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1995"
url_96 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1996"
url_97 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1997"
url_98 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1998"
url_99 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1999"
url_00 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_2000"
url_01 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_2001"
url_02 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_2002"
url_03 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_2003"
url_04 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_2004"
url_05 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_2005"
url_06 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_2006"
url_07 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_2007"
url_08 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_2008"
url_09 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_2009"
url_10 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_2010"
url_11 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_2011"
url_12 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_2012"
url_13 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_2013"
url_14 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_2014"
url_15 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_2015"
url_16 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_2016"
url_17 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_2017"
url_18 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_2018"
url_19 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_2019"
url_20 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_2020"
url_21 = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_2021"
```

```{r,eval=FALSE}
## 'songs' function takes in URL and a number n (1 to 100, default is 10) to output a table of top songs of length n.
songs = function(url,n=10) {
  data = read_html(url)
  tab = data %>% html_nodes("table") %>% .[1]
  tab = tab %>% html_table %>% .[[1]] 
  tab = tab %>% setNames(c("No.", "Title", "Artist(s)"))
  tab = tab[1:n,] 
  return(tab)
}
```

```{r,eval=FALSE}
## Generate tables of top songs for each year and add column specifying year.
## Years 2012 and 2013 were not used.
tab_58 = songs(url_58)
tab_58 = tab_58 %>% mutate(Year = 1958)
tab_59 = songs(url_59)
tab_59 = tab_59 %>% mutate(Year = 1959)
tab_60 = songs(url_60)
tab_60 = tab_60 %>% mutate(Year = 1960)
tab_61 = songs(url_61)
tab_61 = tab_61 %>% mutate(Year = 1961)
tab_62 = songs(url_62)
tab_62 = tab_62 %>% mutate(Year = 1962)
tab_63 = songs(url_63)
tab_63 = tab_63 %>% mutate(Year = 1963)
tab_64 = songs(url_64)
tab_64 = tab_64 %>% mutate(Year = 1964)
tab_65 = songs(url_65)
tab_65 = tab_65 %>% mutate(Year = 1965)
tab_66 = songs(url_66)
tab_66 = tab_66 %>% mutate(Year = 1966)
tab_67 = songs(url_67)
tab_67 = tab_67 %>% mutate(Year = 1967)
tab_68 = songs(url_68)
tab_68 = tab_68 %>% mutate(Year = 1968)
tab_69 = songs(url_69)
tab_69 = tab_69 %>% mutate(Year = 1969)
tab_70 = songs(url_70)
tab_70 = tab_70 %>% mutate(Year = 1970)
tab_71 = songs(url_71)
tab_71 = tab_71 %>% mutate(Year = 1971)
tab_72 = songs(url_72)
tab_72 = tab_72 %>% mutate(Year = 1972)
tab_73 = songs(url_73)
tab_73 = tab_73 %>% mutate(Year = 1973)
tab_74 = songs(url_74)
tab_74 = tab_74 %>% mutate(Year = 1974)
tab_75 = songs(url_75)
tab_75 = tab_75 %>% mutate(Year = 1975)
tab_76 = songs(url_76)
tab_76 = tab_76 %>% mutate(Year = 1976)
tab_77 = songs(url_77)
tab_77 = tab_77 %>% mutate(Year = 1977)
tab_78 = songs(url_78)
tab_78 = tab_78 %>% mutate(Year = 1978)
tab_79 = songs(url_79)
tab_79 = tab_79 %>% mutate(Year = 1979)
tab_80 = songs(url_80)
tab_80 = tab_80 %>% mutate(Year = 1980)
tab_81 = songs(url_81)
tab_81 = tab_81 %>% mutate(Year = 1981)
tab_82 = songs(url_82)
tab_82 = tab_82 %>% mutate(Year = 1982)
tab_83 = songs(url_83)
tab_83 = tab_83 %>% mutate(Year = 1983)
tab_84 = songs(url_84)
tab_84 = tab_84 %>% mutate(Year = 1984)
tab_85 = songs(url_85)
tab_85 = tab_85 %>% mutate(Year = 1985)
tab_86 = songs(url_86)
tab_86 = tab_86 %>% mutate(Year = 1986)
tab_87 = songs(url_87)
tab_87 = tab_87 %>% mutate(Year = 1987)
tab_88 = songs(url_88)
tab_88 = tab_88 %>% mutate(Year = 1988)
tab_89 = songs(url_89)
tab_89 = tab_89 %>% mutate(Year = 1989)
tab_90 = songs(url_90)
tab_90 = tab_90 %>% mutate(Year = 1990)
tab_91 = songs(url_91)
tab_91 = tab_91 %>% mutate(Year = 1991)
tab_92 = songs(url_92)
tab_92 = tab_92 %>% mutate(Year = 1992)
tab_93 = songs(url_93)
tab_93 = tab_93 %>% mutate(Year = 1993)
tab_94 = songs(url_94)
tab_94 = tab_94 %>% mutate(Year = 1994)
tab_95 = songs(url_95)
tab_95 = tab_95 %>% mutate(Year = 1995)
tab_96 = songs(url_96)
tab_96 = tab_96 %>% mutate(Year = 1996)
tab_97 = songs(url_97)
tab_97 = tab_97 %>% mutate(Year = 1997)
tab_98 = songs(url_98)
tab_98 = tab_98 %>% mutate(Year = 1998)
tab_99 = songs(url_99)
tab_99 = tab_99 %>% mutate(Year = 1999)
tab_00 = songs(url_00)
tab_00 = tab_00 %>% mutate(Year = 2000)
tab_01 = songs(url_01)
tab_01 = tab_01 %>% mutate(Year = 2001)
tab_02 = songs(url_02)
tab_02 = tab_02 %>% mutate(Year = 2002)
tab_03 = songs(url_03)
tab_03 = tab_03 %>% mutate(Year = 2003)
tab_04 = songs(url_04)
tab_04 = tab_04 %>% mutate(Year = 2004)
tab_05 = songs(url_05)
tab_05 = tab_05 %>% mutate(Year = 2005)
tab_06 = songs(url_06)
tab_06 = tab_06 %>% mutate(Year = 2006)
tab_07 = songs(url_07)
tab_07 = tab_07 %>% mutate(Year = 2007)
tab_08 = songs(url_08)
tab_08 = tab_08 %>% mutate(Year = 2008)
tab_09 = songs(url_09)
tab_09 = tab_09 %>% mutate(Year = 2009)
tab_10 = songs(url_10)
tab_10 = tab_10 %>% mutate(Year = 2010)
tab_11 = songs(url_11)
tab_11 = tab_11 %>% mutate(Year = 2011)
tab_14 = songs(url_14)
tab_14 = tab_14 %>% mutate(Year = 2014)
tab_15 = songs(url_15)
tab_15 = tab_15 %>% mutate(Year = 2015)
tab_16 = songs(url_16)
tab_16 = tab_16 %>% mutate(Year = 2016)
tab_17 = songs(url_17)
tab_17 = tab_17 %>% mutate(Year = 2017)
tab_18 = songs(url_18)
tab_18 = tab_18 %>% mutate(Year = 2018)
tab_19 = songs(url_19)
tab_19 = tab_19 %>% mutate(Year = 2019)
tab_20 = songs(url_20)
tab_20 = tab_20 %>% mutate(Year = 2020)
tab_21 = songs(url_21)
tab_21 = tab_21 %>% mutate(Year = 2021)
tab_12
```

```{r,eval=FALSE}
## Bind all of the separate year tables together by row to form a single data frame.
## Years 2012 and 2013 were not used.
data_songs = rbind(tab_58, tab_59, tab_60, tab_61, tab_62, tab_63, tab_64, tab_65, tab_66, tab_67, tab_68, tab_69, tab_70, tab_71, tab_72, tab_73, tab_74, tab_75, tab_76, tab_77, tab_78, tab_79, tab_80, tab_81, tab_82, tab_83, tab_84, tab_85, tab_86, tab_87, tab_88, tab_89, tab_90, tab_91, tab_92, tab_93, tab_94, tab_95, tab_96, tab_97, tab_98, tab_99, tab_00, tab_01, tab_02, tab_03, tab_04, tab_05, tab_06, tab_07, tab_08, tab_09, tab_10, tab_11, tab_14, tab_15, tab_16, tab_17, tab_18, tab_19, tab_20, tab_21) 

## Make 'No.' column numeric
data_songs = data_songs %>% transform(No. = as.numeric(No.))
## Group songs by 'No.' in ascending order
data_songs = data_songs %>% group_by(No.) %>% arrange(No.)
## Save data frame
save(data_songs,file="songs.Rda")
```

```{r}
## Load saved data frame for future use
load("songs.Rda")
data_songs
```
